# Generated by tools/gen_tags.nim from doc/tags.md. DO NOT EDIT!

import tags

type
  NifasmInst* = enum
    NoInst
    MovI = (ord(MovTagId), "mov")  ## move instruction
    LeaI = (ord(LeaTagId), "lea")  ## load effective address
    MovapdI = (ord(MovapdTagId), "movapd")  ## move aligned packed double
    MovsdI = (ord(MovsdTagId), "movsd")  ## move scalar double
    AddI = (ord(AddTagId), "add")  ## add instruction
    SubI = (ord(SubTagId), "sub")  ## subtract instruction
    MulI = (ord(MulTagId), "mul")  ## unsigned multiply
    ImulI = (ord(ImulTagId), "imul")  ## signed multiply
    DivI = (ord(DivTagId), "div")  ## unsigned divide
    IdivI = (ord(IdivTagId), "idiv")  ## signed divide
    AddsdI = (ord(AddsdTagId), "addsd")  ## add scalar double
    SubsdI = (ord(SubsdTagId), "subsd")  ## subtract scalar double
    MulsdI = (ord(MulsdTagId), "mulsd")  ## multiply scalar double
    DivsdI = (ord(DivsdTagId), "divsd")  ## divide scalar double
    AndI = (ord(AndTagId), "and")  ## bitwise and
    OrI = (ord(OrTagId), "or")  ## bitwise or
    XorI = (ord(XorTagId), "xor")  ## bitwise xor
    ShlI = (ord(ShlTagId), "shl")  ## shift left
    ShrI = (ord(ShrTagId), "shr")  ## shift right
    SalI = (ord(SalTagId), "sal")  ## shift arithmetic left
    SarI = (ord(SarTagId), "sar")  ## shift arithmetic right
    IncI = (ord(IncTagId), "inc")  ## increment
    DecI = (ord(DecTagId), "dec")  ## decrement
    NegI = (ord(NegTagId), "neg")  ## negate
    NotI = (ord(NotTagId), "not")  ## bitwise not
    CmpI = (ord(CmpTagId), "cmp")  ## compare
    TestI = (ord(TestTagId), "test")  ## test
    SeteI = (ord(SeteTagId), "sete")  ## set byte if equal
    SetzI = (ord(SetzTagId), "setz")  ## set byte if zero
    SetneI = (ord(SetneTagId), "setne")  ## set byte if not equal
    SetnzI = (ord(SetnzTagId), "setnz")  ## set byte if not zero
    SetaI = (ord(SetaTagId), "seta")  ## set byte if above
    SetnbeI = (ord(SetnbeTagId), "setnbe")  ## set byte if not below or equal
    SetaeI = (ord(SetaeTagId), "setae")  ## set byte if above or equal
    SetnbI = (ord(SetnbTagId), "setnb")  ## set byte if not below
    SetncI = (ord(SetncTagId), "setnc")  ## set byte if not carry
    SetbI = (ord(SetbTagId), "setb")  ## set byte if below
    SetnaeI = (ord(SetnaeTagId), "setnae")  ## set byte if not above or equal
    SetcI = (ord(SetcTagId), "setc")  ## set byte if carry
    SetbeI = (ord(SetbeTagId), "setbe")  ## set byte if below or equal
    SetnaI = (ord(SetnaTagId), "setna")  ## set byte if not above
    SetgI = (ord(SetgTagId), "setg")  ## set byte if greater
    SetnleI = (ord(SetnleTagId), "setnle")  ## set byte if not less or equal
    SetgeI = (ord(SetgeTagId), "setge")  ## set byte if greater or equal
    SetnlI = (ord(SetnlTagId), "setnl")  ## set byte if not less
    SetlI = (ord(SetlTagId), "setl")  ## set byte if less
    SetngeI = (ord(SetngeTagId), "setnge")  ## set byte if not greater or equal
    SetleI = (ord(SetleTagId), "setle")  ## set byte if less or equal
    SetngI = (ord(SetngTagId), "setng")  ## set byte if not greater
    SetoI = (ord(SetoTagId), "seto")  ## set byte if overflow
    SetsI = (ord(SetsTagId), "sets")  ## set byte if sign
    SetpI = (ord(SetpTagId), "setp")  ## set byte if parity
    JmpI = (ord(JmpTagId), "jmp")  ## unconditional jump
    JeI = (ord(JeTagId), "je")  ## jump if equal
    JzI = (ord(JzTagId), "jz")  ## jump if zero
    JneI = (ord(JneTagId), "jne")  ## jump if not equal
    JnzI = (ord(JnzTagId), "jnz")  ## jump if not zero
    JgI = (ord(JgTagId), "jg")  ## jump if greater
    JngI = (ord(JngTagId), "jng")  ## jump if not greater
    JgeI = (ord(JgeTagId), "jge")  ## jump if greater or equal
    JngeI = (ord(JngeTagId), "jnge")  ## jump if not greater or equal
    JaI = (ord(JaTagId), "ja")  ## jump if above
    JnaI = (ord(JnaTagId), "jna")  ## jump if not above
    JaeI = (ord(JaeTagId), "jae")  ## jump if above or equal
    JnaeI = (ord(JnaeTagId), "jnae")  ## jump if not above or equal
    CallI = (ord(CallTagId), "call")  ## function call
    RetI = (ord(RetTagId), "ret")  ## return instruction
    PushI = (ord(PushTagId), "push")  ## push to stack
    PopI = (ord(PopTagId), "pop")  ## pop from stack
    NopI = (ord(NopTagId), "nop")  ## no operation
    SyscallI = (ord(SyscallTagId), "syscall")  ## system call
    LabI = (ord(LabTagId), "lab")  ## label definition
    IteI = (ord(IteTagId), "ite")  ## if-then-else structure
    LoopI = (ord(LoopTagId), "loop")  ## loop structure
    StmtsI = (ord(StmtsTagId), "stmts")  ## statement block

proc rawTagIsNifasmInst*(raw: TagEnum): bool {.inline.} =
  raw >= MovTagId and raw <= StmtsTagId

type
  NifasmType* = enum
    NoType
    BoolT = (ord(BoolTagId), "bool")  ## boolean type
    IT = (ord(ITagId), "i")  ## signed integer type of N bits
    UT = (ord(UTagId), "u")  ## unsigned integer type of N bits
    FT = (ord(FTagId), "f")  ## float type of N bits
    PtrT = (ord(PtrTagId), "ptr")  ## pointer to single element
    AptrT = (ord(AptrTagId), "aptr")  ## pointer to array of elements
    ArrayT = (ord(ArrayTagId), "array")  ## array type
    ObjectT = (ord(ObjectTagId), "object")  ## object type definition
    FldT = (ord(FldTagId), "fld")  ## field definition

proc rawTagIsNifasmType*(raw: TagEnum): bool {.inline.} =
  raw >= BoolTagId and raw <= FldTagId and raw != TagEnum(8)

type
  NifasmDecl* = enum
    NoDecl
    TypeD = (ord(TypeTagId), "type")  ## type declaration
    ProcD = (ord(ProcTagId), "proc")  ## proc declaration
    ParamsD = (ord(ParamsTagId), "params")  ## parameters block
    ParamD = (ord(ParamTagId), "param")  ## parameter declaration
    RetsD = (ord(RetsTagId), "rets")  ## return value declaration
    ClobberD = (ord(ClobberTagId), "clobber")  ## clobbered registers list
    BodyD = (ord(BodyTagId), "body")  ## proc body
    VarD = (ord(VarTagId), "var")  ## variable declaration
    RodataD = (ord(RodataTagId), "rodata")  ## read-only data (string/bytes)

proc rawTagIsNifasmDecl*(raw: TagEnum): bool {.inline.} =
  raw in {TypeTagId, ProcTagId, ParamsTagId, ParamTagId, RetsTagId, ClobberTagId, BodyTagId, VarTagId, RodataTagId}

type
  NifasmExpr* = enum
    NoExpr
    SsizeX = (ord(SsizeTagId), "ssize")  ## stack size expression
    DotX = (ord(DotTagId), "dot")  ## field access
    AtX = (ord(AtTagId), "at")  ## array index
    MemX = (ord(MemTagId), "mem")  ## memory reference

proc rawTagIsNifasmExpr*(raw: TagEnum): bool {.inline.} =
  raw in {SsizeTagId, DotTagId, AtTagId, MemTagId}

type
  NifasmOther* = enum
    NoOther
    SO = (ord(STagId), "s")  ## stack slot location tag

proc rawTagIsNifasmOther*(raw: TagEnum): bool {.inline.} =
  raw >= STagId and raw <= STagId

